name: deploy
on:
  push:
    branches:
      - main
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Timezone
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Europe/Madrid"

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: 3.9.2

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Unit Tests
        run: mvn clean package

      - name: Integration Tests
        run: mvn clean verify

      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"   

      - name: Commit and push the badge (if it changed)
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'commit badge'
          add: '*.svg'

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco/

      - name: Rename the artifact
        run: cp target/poc-spring-boot-kafka-0.0.1.jar poc-spring-boot-kafka-0.0.1.jar

      - name: Save the artifact
        uses: actions/upload-artifact@master
        with:
          name: poc-spring-boot-kafka
          path: poc-spring-boot-kafka-0.0.1.jar

  upload-dockerhub:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get the artifact
        uses: actions/download-artifact@master
        with:
          name: poc-spring-boot-kafka

      - name: List files
        run: ls

      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Build the Docker image
        run:  docker build -t ${{secrets.DOCKER_USER}}/poc-spring-boot-kafka --build-arg VERSION=0.0.1 .

      - name: Docker Push
        run: docker push ${{secrets.DOCKER_USER}}/poc-spring-boot-kafka