name: Renovate

on:
  push:
    branches:
      - main
      - master

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Renovate
        uses: renovatebot/github-action@v38.1.6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
