name: Renovate

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Renovate
        uses: renovatebot/action-configure@v1
        with:
          config-path: renovate.json
          token: ${{ secrets.GITHUB_TOKEN }}
