name: Renovate

on:
  push:
    branches:
      - main
      - master

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Renovate
        uses: renovatebot/github-action@v38.1.6
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: 'debug'
          RENOVATE_AUTODISCOVER: true
